@startuml
'https://plantuml.com/class-diagram

class Task {
    - dueDate : LocalDate
    - completeDate : LocalDate
    - description : String
    - person : Person
    - outdoor : boolean
    - taskSize : String
}
Task --> Person

class Person {
    - name : String
}

class TaskOverview {
    - tasksToDo : List<Task>
    - tasksCompleted : List<Task>
    + addTask(task : Task)
    + completeTask(task : Task) : void
}
TaskOverview o-- Task

class TaskUtility {
    - SMALL : String
    - MEDIUM : String
    - LARGE : String
}



@enduml